plugins { id 'com.android.application' }

android {
    namespace 'com.juanpablo.amdvsintel'
    compileSdk 35

    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'amdintel123'
            keyAlias 'amdintel'
            keyPassword 'amdintel123'
        }
    }

    defaultConfig {
        applicationId 'com.juanpablo.amdvsintel'
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName '1.1.2'
    }

    buildTypes {
        debug {
            debuggable true
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
